package tech.hirsun.orderfusion.utils;

import org.apache.commons.codec.digest.DigestUtils;
import org.springframework.beans.factory.annotation.Value;

public class HashUtil {

    /**
     * This is a fixed salt, which is used to prevent rainbow table attack.
     * length >= 8
     */
    private static final String fixedSalt = "o1dr7u5io9";

    /**
     * @param str: the string to be hashed
     * @return the hashed string of SHA256
     */
    public static String sha256(String str) {
        return DigestUtils.sha256Hex(str);
    }

    /**
     * @param plainPass: the password input by the user in apps
     * @return the password after formPlainPassToMidPass
     */
    public static String formPlainPassToMidPass(String plainPass) {
        String midPass = String.valueOf(fixedSalt.charAt(0)) + fixedSalt.charAt(6) + plainPass + fixedSalt.charAt(4) + fixedSalt.charAt(7);
        return sha256(midPass);
    }

    /**
     * @param midPass: the password after formPlainPassToMidPass
     * @param randomSalt: the random salt generated by the server, must >= 6
     */
    public static String formMidPassToDBPass(String midPass, String randomSalt) {
        String finalPass = String.valueOf(randomSalt.charAt(2)) + randomSalt.charAt(5) + midPass + randomSalt.charAt(3) + randomSalt.charAt(1);
        return sha256(finalPass);
    }

    /**
     * @param plainPass: the password input by the user in apps
     * @param randomSalt: the random salt generated by the server, must >= 6
     * @return the password for database
     */
    public static String formPlainPassToDBPass(String plainPass, String randomSalt) {
        String midPass = formPlainPassToMidPass(plainPass);
        return formMidPassToDBPass(midPass, randomSalt);
    }

    public static void main(String[] args) {
        System.out.println(formPlainPassToMidPass("123456"));
        System.out.println(formMidPassToDBPass("0b39ea1a37c546ff91371ec1f8ab371ae62aedf1b1b5023492511f53fff5ae29","ah28as"));
    }

}
